name: Docker Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ethanscully
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Image
      run: |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t ethanscully/ollama-discord:${GITHUB_REF_NAME#v} \
        -t ethanscully/ollama-discord:latest \
        --push .

    - name: Create build files
      run: |
        docker run --rm \
        -v $(pwd):/mnt/ -w /mnt/ \
        -t golang bash -c '
        git config --global --add safe.directory "*"
        export CGO_ENABLED=0
        export GOOS=linux
        export GOARCH=amd64
        go build -ldflags="-s -w" -o ollama-discord-linux-amd64
        export GOARCH=arm64
        go build -ldflags="-s -w" -o ollama-discord-linux-arm64
        export GOOS=windows
        export GOARCH=amd64
        go build -ldflags="-s -w" -o ollama-discord-win-amd64.exe
        export GOARCH=arm64
        go build -ldflags="-s -w" -o ollama-discord-win-arm64.exe
        export GOOS=darwin
        export GOARCH=amd64
        go build -ldflags="-s -w" -o ollama-discord-macos-amd64
        export GOARCH=arm64
        go build -ldflags="-s -w" -o ollama-discord-macos-arm64'

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ollama-discord-linux-amd64
          ollama-discord-linux-arm64
          ollama-discord-win-amd64.exe
          ollama-discord-win-arm64.exe
          ollama-discord-macos-amd64
          ollama-discord-macos-arm64
